### ISSUE TITLE
intgrate new model with the code

### ISSUE THREAD

**Issue by hakS07** [toniz/deeplab-on-ios#2]
@toniz 
thnx for the project, it was really helpful for me, i have tried to put my retrained model on the code but I got an error if you don't mind can you check it with me??

error > EXC_BAD_ACCESS 

i have trained deeplab model on new object and its work with detection
i was able to successfully convert the model with the following command:
`toco --output_file=model.tflite --input_file=prozen_inference_graph.pb --input_arrays=ImageTensor --output_arrays=SemanticPredictions --input_shapes=1,513,513,3 --inference_input_type=QUANTIZED_UINT8 --inference_type=FLOAT --mean_values=128 --std_dev_values=127 --allow_custom_ops --post_training_quantize
`
![Sans titre 2](https://user-images.githubusercontent.com/34586193/60468266-031c9680-9c51-11e9-91a6-e34f68607d53.png)

**Comment by toniz** [comment]
your model input shape is: --input_shapes=1,513,513,3
So change 
cv::resize(frame, small, cv::Size(257, 257), 0, 0, CV_INTER_LINEAR);
to:
cv::resize(frame, small, cv::Size(513, 513), 0, 0, CV_INTER_LINEAR);

**Comment by hakS07** [comment]
@toniz thnx it works now
